### ISSUE TITLE
How to run Watchit gateway when I already run IPFS node?

### ISSUE THREAD

**Issue by kodxana** [ZorrillosDev/watchit-gateway#25]
I have local running node inside docker container. How do I setup gateway without making another copy of IPFS?

**Comment by geolffreym** [comment]
Hi @kodxana, thank you for commit an issue in watchit-gateway. 
Do you have a running node using docker and you need keep using the same node with watchit-gateway?

**Comment by kodxana** [comment]
> Hi @kodxana, thank you for commit an issue in watchit-gateway.
> Do you have a running node using docker and you need keep using the same node with watchit-gateway?

Yes cause I already store content on that node and would be problem to move it to new node.

**Comment by geolffreym** [comment]
Which ports are you using in your current node? defaults?

**Comment by kodxana** [comment]
> Which ports are you using in your current node? defaults?

Custom cause some ports are used for other services

```
4001:4001  5001:5001  85:80  9980:8080
```

**Comment by kodxana** [comment]
> > Which ports are you using in your current node? defaults?
> 
> Custom cause some ports are used for other services
> 
> ```
> 4001:4001  5001:5001  85:80  9980:8080
> ```

This ports are exposed ones from my host

**Comment by geolffreym** [comment]
you could run watchit_migrator removing temporary depends_on: watchit_ipfs. It is not the cleanest way to do it, but it is the quickest solution.

**Comment by kodxana** [comment]
So something like this?

```
version: '3'
services:
  watchit_migrator:
    build: .
    image: gmena/migrate:v1.0.31
    container_name: watchit_migrator
    command: python3 main.py
    links:
      - "watchit_mongodb:mongodb"
    volumes:
      - .:/data/watchit
      - ./data/watchit/node_modules
    env_file:
      - .env
    depends_on:
      - watchit_mongodb
      - watchit_orbitdb_api

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  watchit_orbitdb_api:
    image: phillmac/orbit-db-http-api-dev:debug
    restart: unless-stopped
    command: [ "node", "--trace-warnings", "src/cli.js", "api", "--debug" ]
    environment:
      IPFS_HOST: 'watchit_ipfs'
      ORBITDB_DIR: '/orbitdb'
      FORCE_HTTP1: 'true'
      ANNOUNCE_DBS: 'true'
      LOG: 'DEBUG'
    ports:
      - 127.0.0.1:3001:3000/tcp
    volumes:
      - ./orbitdb:/orbitdb
```
